import json
import os
import re
import sys

# Configure standard output to handle UTF-8 cleanly on Windows
if sys.platform == 'win32' and hasattr(sys.stdout, 'reconfigure'):
    try:
        sys.stdout.reconfigure(encoding='utf-8')
    except Exception:
        pass


def parse_txt_file(filepath):
    """Parses a question text file into a list of question objects."""
    questions = []
    try:
        with open(filepath, 'r', encoding='utf-8') as file:
            lines = file.readlines()
            
        current_q = None
        options = []
        
        for line in lines:
            line_clean = line.strip()
            if not line_clean:
                continue
                
            if line_clean.startswith("### Question") or re.match(r"^###\s+Question", line_clean, re.IGNORECASE):
                if current_q:
                    current_q['options'] = options
                    current_q['type'] = 'mcq' if len(options) > 0 else 'text'
                    questions.append(current_q)
                current_q = {'question': '', 'answer': '', 'image': None, 'type': 'mcq'}
                options = []
            elif line_clean.startswith("IMAGE:"):
                if current_q is not None:
                    current_q['image'] = line_clean.split("IMAGE:", 1)[1].strip()
            elif re.match(r"^[A-D]\)", line_clean):
                options.append(line_clean)
            elif line_clean.startswith("Answer:"):
                if current_q is not None:
                    current_q['answer'] = line_clean.split("Answer:", 1)[1].strip()
            elif current_q is not None:
                # Safely append multi-line question text
                cleaned_text = re.sub(r"^###\s*", "", line_clean)
                if current_q['question'] == '':
                    current_q['question'] = cleaned_text
                else:
                    current_q['question'] += " " + cleaned_text
                    
        if current_q:
            current_q['options'] = options
            current_q['type'] = 'mcq' if len(options) > 0 else 'text'
            questions.append(current_q)

            
    except Exception as e:
        print(f"   ⚠️ Warning reading {filepath}: {e}")
        
    return questions

def clean_title(filename):
    """Turns filename like 'Organic_Chemistry_Lecture_1.txt' into 'Organic Chemistry Lecture 1'."""
    base = os.path.splitext(filename)[0]
    # Replace underscores and multiple dashes with spaces
    title = re.sub(r'[_]+', ' ', base).strip()
    return title

def generate_id(filename):
    """Generates a URL/DOM-safe unique ID for the lecture."""
    base = os.path.splitext(filename)[0].lower()
    return re.sub(r'[^a-z0-9]+', '_', base).strip('_')

def build_all_exams():
    print("=" * 55)
    print("📚 Exam Builder - Multi-Lecture Question Compiler")
    print("=" * 55)
    
    # Scan for all .txt files excluding requirements.txt
    txt_files = [
        f for f in os.listdir('.') 
        if f.endswith('.txt') and f.lower() != 'requirements.txt'
    ]
    txt_files.sort()
    
    if not txt_files:
        print("❌ No question .txt files found in this folder.")
        return
        
    all_exams = []
    print(f"🔍 Discovered {len(txt_files)} question file(s):\n")
    
    for filename in txt_files:
        filepath = os.path.join('.', filename)
        questions = parse_txt_file(filepath)
        title = clean_title(filename)
        exam_id = generate_id(filename)
        
        all_exams.append({
            'id': exam_id,
            'title': title,
            'filename': filename,
            'count': len(questions),
            'questions': questions
        })
        print(f"   ✅ [{len(questions):>3} questions]  {title} ({filename})")
        
    payload = {
        'totalExams': len(all_exams),
        'exams': all_exams
    }
    
    # 1. Output exam_data.json
    with open('exam_data.json', 'w', encoding='utf-8') as outfile:
        json.dump(payload, outfile, ensure_ascii=False, indent=4)
        
    # 2. Output exam_data.js for native local browser loading without CORS issues
    with open('exam_data.js', 'w', encoding='utf-8') as jsfile:
        js_content = f"/* Auto-generated by builder.py - Do not edit manually */\nwindow.EXAM_DATABASE = {json.dumps(payload, ensure_ascii=False, indent=4)};\n"
        jsfile.write(js_content)
        
    print("\n" + "-" * 55)
    print("📁 Saved: exam_data.json")
    print("📁 Saved: exam_data.js (enables direct double-click in browser)")
    print("🎉 All set! Open or refresh index.html to select your lecture.")
    print("=" * 55)

if __name__ == '__main__':
    build_all_exams()